# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Personal Web"
license = "MIT"
licenselink = "https://github.com/Hugo-Leung/personal-web/blob/master/LICENSE"
description = "Personal Web is a simple Hugo template to build a personal website including portfolio and blog sections. It will mainly suit freelancers who want to showcase their work."
homepage = "https://github.com/Hugo-Leung/personal-web"
tags = ["portfolio", "blog", "post", "personal", "freelancer", "developer"]
features = []

[author]
  name = "Ching Him Leung"
[original]
  name = "Baptiste Jacquemet"
  homepage = "https://baptistej.com"
  repo = "https://github.com/baptistej/personal-web"
